"""Initial migration

Revision ID: 2ba95f48081a
Revises: 
Create Date: 2025-04-22 17:30:44.930000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ba95f48081a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active_location_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_user_preferences_active_location', 'locations', ['active_location_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_preferences', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_preferences_active_location', type_='foreignkey')
        batch_op.drop_column('active_location_id')

    # ### end Alembic commands ###
