"""Add login_token and token_expiry to User

Revision ID: 5ec4d157c029
Revises: 
Create Date: 2025-07-14 09:12:59.857903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ec4d157c029'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('login_token', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('token_expiry', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint('uq_users_login_token', ['login_token'])
        batch_op.drop_column('registration_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registration_date', sa.DATETIME(), nullable=True))
        batch_op.drop_constraint('uq_users_login_token', type_='unique')
        batch_op.drop_column('token_expiry')
        batch_op.drop_column('login_token')

    # ### end Alembic commands ###
